### ISSUE TITLE
Error: export 'EmailBuilderHistoryHostDirective' (imported as 'i2$1') was not found in '@wlocalhost/ngx-email-builder'

### ISSUE THREAD

**Issue by h-pires** [wanoo21/ngb.email#8]
this is the error that happens when using i18n in angular 16...
"./node_modules/@wlocalhost/ngx-md-email-builder/fesm2022/wlocalhost-ngx-md-email-builder.mjs:3237:127-164 - Error: export 'EmailBuilderHistoryHostDirective' (imported as 'i2$1') was not found in '@wlocalhost/ngx-email-builder' (possible exports: AIPAlign, AIPBackground, AIPBorder, AIPColor, AIPEmailBody, AIPEmailBuilderAside, AIPEmailBuilderBlock, AIPEmailBuilderComponent, AIPEmailBuilderHistoryService, AIPEmailBuilderMiddlewareService, AIPEmailBuilderRestService, AIPEmailBuilderService, AIPEmailBuilderStorageService, AIPFon t, AIPImageUpload, AIPLineHeight, AIPLink, AIPMargin, AIPPadding, AIPStructure, AIPTemplateList, AIPValueChanged, AIPWidthHeight, ApplyMiddlewarePipe, ButtonBlock, ColumnStylesPipe, DefaultEmailBuilderHistoryService, DefaultIPEmailBuilderMiddlewareService, DefaultIPEmailBuilderRestService, DefaultIPEmailBuilderService, DividerBlock, HtmlBlock, IPE mail, IPEmailBuilderColumnDirective, IPEmailBuilderDynamicDirective, IPEmailBuilderHistoryActionDirective, IPEmailBuilderHistoryHostDirective, IPEmailBuilderSettingsDirective, IPEmailBuilderStructuresDirective, IPEmailBuilderTextEditorDirective, IPEmailBuilderTextEditorMenuDirective, IPHistoryModelDirective, ImageBlock, IpCanPipe, IpPreviewLinkPipe, NavigationBlock, NgxEmailBuilderModule, SocialBlock, SocialPathPipe, SpacerBlock, Structure, TemplateThumbPathPipe, TextBlock, ToBodyBlockPipe, ToBodyStructurePipe, ToHistoryOptionsPipe, addDefaultBlock, addNewIPEmailBuilderBlock, addToStore, cloneDeep, createBackground, createBorder, createFont, createLineHeight, createMargin, createPadding, createWidthHeight, debounce, defaultColumnsOptions, defaultsDeep, getFromStore, mergeObjects, randomString, withConfig)"

**Comment by wanoo21** [comment]
Hey @h-pires, I'm not sure I can reproduce it! what version of `@wlocalhost/ngx-md-email-builder` do you try to install?
